import SwiftUI
import UIKit
import ToothBuddyCore

/// Renders a `ReportData` (pure, tested in Core) to a PDF. Rendering itself is
/// smoke-only per Spec 02 §6.7; the numbers come from `ReportBuilder`.
enum ReportPDFRenderer {

    static func render(_ data: ReportData) -> Data {
        let pageW: CGFloat = 612, pageH: CGFloat = 792          // US Letter
        let margin: CGFloat = 48
        let renderer = UIGraphicsPDFRenderer(
            bounds: CGRect(x: 0, y: 0, width: pageW, height: pageH))

        let df = DateFormatter()
        df.dateStyle = .medium

        return renderer.pdfData { ctx in
            ctx.beginPage()
            var y: CGFloat = margin

            func draw(_ s: String, _ size: CGFloat, _ weight: UIFont.Weight,
                      _ color: UIColor = .black) {
                (s as NSString).draw(
                    at: CGPoint(x: margin, y: y),
                    withAttributes: [
                        .font: UIFont.systemFont(ofSize: size, weight: weight),
                        .foregroundColor: color
                    ])
                y += size + 10
            }

            draw("ToothBuddy — Brushing Report", 22, .bold)
            draw(data.profileName, 16, .semibold, .darkGray)
            draw("\(df.string(from: data.start))  –  \(df.string(from: data.end))",
                 12, .regular, .gray)
            y += 8

            draw("Sessions: \(data.totalSessions)", 14, .regular)
            draw("Thorough (every area, full time): \(data.thoroughSessions) / \(data.totalSessions)",
                 14, .regular)
            draw("Camera-verified: \(data.verifiedSessions) / \(data.totalSessions)",
                 14, .regular)
            draw("Average active time: \(Self.mmss(data.avgActiveSeconds))", 14, .regular)
            draw("Active days: \(data.activeDays) / \(data.totalDays)  (\(data.completionPercent)%)",
                 14, .regular)
            draw("Current streak: \(data.currentStreak)   ·   Longest: \(data.longestStreak)",
                 14, .regular)
            y += 6
            draw("Camera-verified sessions were confirmed by the front camera. Guided sessions",
                 10, .regular, .gray)
            draw("are self-paced with no video — they are not camera-confirmed.",
                 10, .regular, .gray)
            y += 8
            draw("Daily calendar  ·  green = thorough, blue = brushed, gray = none", 13, .semibold)

            // Calendar grid: 14 cells per row.
            let perRow = 14
            let cell: CGFloat = 26, gap: CGFloat = 4
            var gx = margin, gy = y
            for (i, d) in data.days.enumerated() {
                let color: UIColor = d.thorough
                    ? UIColor.systemGreen
                    : (d.active ? UIColor.systemBlue : UIColor.systemGray5)
                let rect = CGRect(x: gx, y: gy, width: cell, height: cell)
                let path = UIBezierPath(roundedRect: rect, cornerRadius: 5)
                color.setFill()
                path.fill()
                gx += cell + gap
                if (i + 1) % perRow == 0 { gx = margin; gy += cell + gap }
                if gy > pageH - margin { break }
            }

            let footY = pageH - margin
            ("Generated by ToothBuddy" as NSString).draw(
                at: CGPoint(x: margin, y: footY),
                withAttributes: [.font: UIFont.systemFont(ofSize: 10),
                                 .foregroundColor: UIColor.lightGray])
        }
    }

    private static func mmss(_ s: Int) -> String {
        String(format: "%d:%02d", max(0, s) / 60, max(0, s) % 60)
    }

    /// Render to a temp file for the share sheet; returns the URL.
    static func writeTempPDF(_ data: ReportData) -> URL? {
        let pdf = render(data)
        let safeName = data.profileName.replacingOccurrences(of: "/", with: "-")
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("ToothBuddy-\(safeName).pdf")
        do { try pdf.write(to: url); return url } catch { return nil }
    }
}

/// Minimal UIActivityViewController wrapper for sharing the generated PDF.
struct ShareSheet: UIViewControllerRepresentable {
    let items: [Any]
    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: items, applicationActivities: nil)
    }
    func updateUIViewController(_ vc: UIActivityViewController, context: Context) {}
}
